### ISSUE TITLE
Customizing input file

### ISSUE THREAD

**Issue by jonathanqueiroz** [jgile/vue-csv-import#12]
There's a another way to customize the input file style and other messages like "File input is invalid"?

I need to put the button and messages in portuguese. I managed to apply some styles in the input file, but I could not customize the parent divs and "change" events.

**Comment by jgile** [comment]
accepting PRs

**Comment by filsh** [comment]
https://github.com/jgile/vue-csv-import/pull/39

**Comment by jgile** [comment]
updated in new version.  much more customizable.
