### ISSUE TITLE
Unable to use component with vuetify

### ISSUE THREAD

**Issue by goranculibrk** [jgile/vue-csv-import#16]
Hi there, I'm having issues with adding vue-csv-import to vuetify app. 
I'm using datatables component which have prop headers as well. 
When I add your example to my app I keep getting this error.

I've tried adding headers option to the component but without success
```javascript
[Vue warn]: Invalid prop: type check failed for prop "value". Expected Array, got String with value "".
found in
---> <VueCsvImport>
```

**Comment by daksamit** [comment]
What version ov vuetify do you use?

**Comment by ssnatu** [comment]
Hi @goranculibrk @jgile I've installed this today, I've got the same error. Did you find any solution for this?

```
[Vue warn]: Invalid prop: type check failed for prop "value". Expected Array, got String with value "".

found in

---> <VueCsvImport>
       <CsvImport> at resources/js/components/csv-import.vue
         <Root>
```

**Comment by phronesis** [comment]
> Hi @goranculibrk @jgile I've installed this today, I've got the same error. Did you find any solution for this?
> 
> ```
> [Vue warn]: Invalid prop: type check failed for prop "value". Expected Array, got String with value "".
> 
> found in
> 
> ---> <VueCsvImport>
>        <CsvImport> at resources/js/components/csv-import.vue
>          <Root>
> ```

I am experiencing the same error.

**Comment by amymaraisane7f** [comment]
@goranculibrk  @ssnatu @jgile   I solved this by setting the v-model for vue-csv-import equal to an empty array when the component loads. This will later be filled in with whatever the user uploads.

**Comment by thealoneprogrammer** [comment]
I have used this with vuetify, I am able to get it to work. But the stylings are not applied when used with vuetify.

**Comment by amymaraisane7f** [comment]
- Update- I had to abandon this library because when I would upload a document, it was not getting into the v-model for the vue-csv-import component. I am working with papa parse directly now.

**Comment by InToSSH** [comment]
I got it working with Vuetify, only problem I have is with the `hasHeaders` slot. I wanted to use `<v-checkbox>` but that doesn't seem to work.
```
                        <template slot="hasHeaders" slot-scope="{headers, toggle}">
                            <v-checkbox
                                :value="headers"
                                @change="toggle"
                                label="Headers?"
                                color="success"
                            ></v-checkbox>
                        </template>
```
I tried even with `@change="toggle()"`, `@change="val => toggle(val)"`, `@change="val => toggle({target: {value: val}}"` but no luck.

**Comment by InToSSH** [comment]
@thealoneprogrammer yes, styles are gone, but I just replaced all with vuetify components:
```
<vue-csv-import
                        v-model="import_form.csv_data"
                        :map-fields="csv_fields"
                        auto-match-fields
                        can-ignore
                        table-select-class="import-table-select"
                    >
                        <template slot="hasHeaders" slot-scope="{headers, toggle}">
                            <v-checkbox
                                :value="headers"
                                @change="toggle"
                                label="Headers?"
                                color="success"
                            ></v-checkbox>
                        </template>

                        <template slot="thead">
                            <tr>
                                <th colspan="2">Column mapping</th>
                            </tr>
                            <tr>
                                <th>System</th>
                                <th>CSV file</th>
                            </tr>
                        </template>

                        <template slot="next" slot-scope="{load}">
                            <v-btn
                                @click.prevent="load"
                                color="success"
                                class="mt-5"
                                outlined
                                small
                            >Next</v-btn>
                        </template>

                        <template slot="submit" slot-scope="{submit}">
                            <v-btn
                                @click.prevent="submit"
                                color="success"
                                class="mt-5"
                            >Submit</v-btn>
                        </template>
                    </vue-csv-import>

<style lang="scss">
.import-table-select {
    border: 1px solid black !important;
    padding: 3px 8px !important;
    margin: 2px 5px !important;
    border-radius: 0px !important;
    -moz-appearance: auto !important;
    -webkit-appearance: auto !important;
}
</style>
```

**Comment by imcoffeefreak** [comment]
@InToSSH Stylings for Choose File field is working absolutely fine. But the issue of styling in dropdown is still the same
![Uploading Screenshot (28).png…]()

**Comment by jgile** [comment]
Vue 3 version is much more flexible.  I will accept PRs for version 2 to

**Comment by InToSSH** [comment]
> Vue 3 version is much more flexible. I will accept PRs for version 2 to

It is, but Vue 3 is not yet supported by Vuetify and it looks like it won't be for a while.
