### ISSUE TITLE
Simple step missing: how to run without compiler error

### ISSUE THREAD

**Issue by dylannirvana** [jgile/vue-csv-import#2]
Hi John, but could you give a brief explanation on how to run this to someone who is new to Vue? When I attempt to run with vue-cli, I get this error:

`webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:588 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)
warn @ webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:588
`
Thank you!

**Comment by jgile** [comment]
updated to use with vue-cli.  download and run "npm run server"
