### ISSUE TITLE
Ability to pass http headers prop

### ISSUE THREAD

**Issue by Jhilan** [jgile/vue-csv-import#20]
Would be nice to be able to pass optional http headers prop to the component something like
`<vue-csv-import :http-headers="{'key': 'val'}"></vue-csv-import>`

with minimal changes to `VueCsvImport.vue`
``` 
httpHeaders: {
   type: Object,
   default() { return {}; }
 },  
.
.
.
axios.post(this.url, this.form, { headers: this.httpHeaders })          
```

**Comment by jgile** [comment]
You can always set axios headers outside of the component.  For example:

```
window.axios.defaults.headers.common = {
    'X-Requested-With': 'XMLHttpRequest'
};
```

**Comment by Jhilan** [comment]
Thanks! jgile.
