### ISSUE TITLE
CSV Mapping should auto-match fields

### ISSUE THREAD

**Issue by dylanwatsonsoftware** [jgile/vue-csv-import#22]
When importing a file, if the fields in the header match any of the names of the fields being mapped, it should automatically select those fields.

This is a huge pain if you have more than a few fields.

**Comment by scramatte** [comment]
I need it this feature too.  Save lot of works ...
+1

**Comment by njogz** [comment]
Alternatively you should be able to pass a mapper object.

**Comment by jgile** [comment]
#24
