### ISSUE TITLE
Feature request: set delimiter, enclosre, escape,...

### ISSUE THREAD

**Issue by scramatte** [jgile/vue-csv-import#23]
Would be nice to add support to  set delimiter, enclosure, escape, max lines and automapping fields.

**Comment by RoelRoel** [comment]
Yes, the feature of setting a seperator or delimiter is what I really need because in countries where we use ',' as a decimal sign we use ; as a delimiter!

**Comment by jgile** [comment]
new version accepts a full config object for papaparse.
