### ISSUE TITLE
How to get Callback response

### ISSUE THREAD

**Issue by ibadass** [jgile/vue-csv-import#34]
Hello,

First of all, great work ! This plugin is great !
But I've some diffculties to implement it. I don't understand how callback/finally/catch methods works, can you help me ?
I set url option to my API, and set a callback method in order to get the response from my service, but nothing happen.
Thanks for your answer.

**Comment by jgile** [comment]
set the callback as a function and the response will be given to you as a parameter.  callback, finally, and catch just correspond with axios accordingly.

the callback will only be called if the request is successful.  
if an error, catch is called
finally is always called.

**Comment by ibadass** [comment]
OK, I edit my synthaxe, and it's OK now !

Thanks !

**Comment by maximusblade** [comment]
How did you resolve this.
Do you have a code snippet?

**Comment by ibadass** [comment]
Hello,
There is my code :
`<vue-csv-import v-model="file"`
`:headers="true"`
`:url="importUrl"`
`:map-fields="json_fields"`
`:autoMatchFields="true"`
`:autoMatchIgnoreCase="true"`
`:callback="getCSVResponse">`

My URL (import Url) is calling my service (in my API) to import data from the file uploaded.
And when the service return a response, I handle it with the callback method (get CSV Response).

Is it OK for you ?

**Comment by maximusblade** [comment]
@ibadass Thank you this works !
