### ISSUE TITLE
without url access json data

### ISSUE THREAD

**Issue by GawandeC** [jgile/vue-csv-import#36]
i dont want to pass the url instead I need the data in v-model 
but currently v-model is null
     <vue-csv-import v-model="csv" :map-fields="['question', 'answer']" >
here this.csv or {{csv}} is null or undefined.

any idea????

**Comment by spacewaffle** [comment]
Are you using autoMatchFields? There was a bug reported on the latest version recently on that feature which will be fixed by this pr https://github.com/jgile/vue-csv-import/pull/37. For now, turn off autoMatchFields until the pr is accepted or use the old 3.1.0 version.

**Comment by jgile** [comment]
v-model is bound to the parsed csv object.
