### ISSUE TITLE
dist dir not up-to-date on NPM

### ISSUE THREAD

**Issue by kebray-edxt** [jgile/vue-csv-import#38]
While the source code for v3.3.0 is up-to-date when doing an `npm install vue-csv-import` with dependency set to `"vue-csv-import": "^3.3.0"` in my Vue app package.json, the `dist` directory for `vue-csv-import` in `node_modules` is not the latest build of that source.  I discovered this while trying to pass the props of `autoMatchFields` and `autoMatchIgnoreCase` which do not work when using as a Plugin in a standard Vue application.  Those props are missing from `vue-csv-import/dist/VueCsvImport.common.js` unless you build from source.  After building from source, those props work correctly.

**Comment by jgile** [comment]
rebuilt and published.
