### ISSUE TITLE
Load button doesn't seem to appear when every field gets matched up with CSV field

### ISSUE THREAD

**Issue by Kevin-DDR** [jgile/vue-csv-import#40]
The load button doesn't seem to appear when every field gets matched up by the autoMatchFields.
Changing the corresponding match in the table doesn't make it appear either.

**Comment by jgile** [comment]
please provide the code to reproduce

**Comment by Kevin-DDR** [comment]
This is waht happens when every field get matched.
![Capture d’écran 2020-07-13 à 10 30 34](https://user-images.githubusercontent.com/12892650/87281879-f8e3d800-c4f3-11ea-8d24-bad36ac36b0d.png)
Whereas the button properly renders when at least one field doesn't get automatically matched up.

```
<div class="row">
        <div class="col-md-12">
          <vue-csv-import
            v-if="text_loaded"
            v-model="parsedCSV"
            :map-fields="fields"
            :checkboxClass="checkboxClass"
            :loadBtnText="loadBtnText"
            :buttonClass="loadBtnClass"
            autoMatchFields="true"
            autoMatchIgnoreCase="true"
            :headers="hasHeaders"
          >
            <template slot="hasHeaders" slot-scope="{headers, toggle}">
              <label class="checkbox_csv" style="display: none;"></label>
            </template>
            <template slot="thead">
              <tr>
                <th>{{text.field}}</th>
                <th>{{text.field_CSV}}</th>
              </tr>
            </template>
          </vue-csv-import>
        </div>
      </div>
```

(hasHeaders is equal to `true`)

Trying to change a field's association doesn't make the button appear either. The only way to make it appear is by providing a file with a column that doesn't match with one of the required fields.

**Comment by Kevin-DDR** [comment]
Here's the file I used, had to convert it to a XLSX so I could upload it to Github.
[kb-test.xlsx](https://github.com/jgile/vue-csv-import/files/4911256/kb-test.xlsx)

**Comment by spacewaffle** [comment]
Try updating to the latest version. There was a bug in a previous version that did this.

**Comment by Glenn-Domin** [comment]
That's definitely what it sounds like. Updating would fix it if it's the issue I had. `autoMatchFields` was only added recently.

**Comment by Kevin-DDR** [comment]
Just tried with the latest version, and it did the trick ! Thanks !
