### ISSUE TITLE
Reset the form

### ISSUE THREAD

**Issue by mastazi** [jgile/vue-csv-import#41]
I'm using `v-model`, not `url` (because I need to manipulate the data before sending it to the server).
When I'm done and I want to process a second file, how  can I reset the form?

**Comment by mastazi** [comment]
I have temporarily solved by passing a `resetKey` to the `:key` prop like so:

using a `:key` prop in the child component:

```
             <vue-csv-import
                :key="resetKey"
                //...
              >
              </vue-csv-import>
```
of course `resetKey` needs to be present in your component's `data`...

```
data() {
    return {
      resetKey: 1,
    }
```
and then we reset the state by changing the key:

```
  resetForm() {
      let key = this.resetKey;
      this.resetKey = key + 1;
    },
```

I think this topic should be addressed in the readme. The above technique is taken from this article: https://michaelnthiessen.com/force-re-render/

**Comment by jgile** [comment]
reloading the component like this works.  you can also use HTMLFormElement.reset().

https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset
