### ISSUE TITLE
Upgrade from 3.3.2 to 3.3.3 it shows, This dependency was not found:  * vue-csv-import in ./src/main.js

### ISSUE THREAD

**Issue by palanideveloper** [jgile/vue-csv-import#49]
This dependency was not found:

* vue-csv-import in ./src/main.js

To install it, you can run: npm install --save vue-csv-import

**Comment by jontybrook** [comment]
Same issue here

**Comment by projectn3xt** [comment]
Same issue here

**Comment by Dick-Masterson** [comment]
Really like the look of this package but getting This Dependency was not found error. Using version 3.3.3

**Comment by jgile** [comment]
updated 3.3.5.

npm i --save --force vue-csv-import@3.3.5
