### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by ardeay** [jgile/vue-csv-import#5]
I was not able to get the demo to run. The unpack dist link is broken. 

Thanks for the effort, I look forward to seeing it run.

**Comment by fjoalland** [comment]
Still not working

**Comment by SnehaSadhwani** [comment]
Here is the link for woking demo of this component
https://vuejsexamples.com/vue-js-component-to-handle-csv-uploads-with-field-mapping/

**Comment by jgile** [comment]
fixed
