### ISSUE TITLE
Changing file with fields mapping could let container know

### ISSUE THREAD

**Issue by MartinZedify** [jgile/vue-csv-import#51]
When I use :autoMatchFields="true" and change file then my container element is not told about the change as it is on loading the first file. It would be convenient to notify the container.

I found that by adding 
```
                    _this.$emit('input', this.csv);
```
at line 239 in VueCsvImport.vue, at the end of the callback for the readFile call in the load() method, then the container is notified about the new data.

i.e.
```
            load() {
                const _this = this;

                this.readFile((output) => {
                    console.log('readFile callback')
                    _this.sample = get(Papa.parse(output, { preview: 2, skipEmptyLines: true }), "data");
                    _this.csv = get(Papa.parse(output, { skipEmptyLines: true }), "data");
                    _this.$emit('input', this.csv);
                });
            },
```

**Comment by jgile** [comment]
this is be design as that is not considered the input event with this component.  this is also for the old version of component so marking as closed.
