### ISSUE TITLE
Comma is used as delimiter, even though semicolon has been set as delimiter in vue.config.js file.

### ISSUE THREAD

**Issue by jmath1as** [jgile/vue-csv-import#52]
I'm importing a csv file that is separated by semicolons but contains a lot  of commata as well. Probably there are more commata than semicolons in the file. Those commata are part of the stored data as one column of the file contains a PostgreSQL path.
When the column with the PostgreSQL paths is removed, the file is imported correctly.

I include the csv file as attachment.
[automaten.zip](https://github.com/jgile/vue-csv-import/files/5483136/automaten.zip)

**Comment by jgile** [comment]
you cannot configure the delimiter in vue.config.js.  It would have to be passed to the component directly.
