### ISSUE TITLE
Module not found: Error: Can't resolve 'vue-csv-import'

### ISSUE THREAD

**Issue by lucaford** [jgile/vue-csv-import#58]
Hello,
We updated to version 3.3.5 and when we want to run our production build this appears:
`Module not found: Error: Can't resolve 'vue-csv-import'`
We tried with 3.3.7 and same problem. 
It was working fine before running yarn and updating.

vue version:
`"vue": "^2.5.17"`

*fyi: the library is working just fine when we run it locally. We can import contacts without any problem. The issue comes when we try to run our production build with webpack.

**Comment by lucaford** [comment]
We solved this issue by importing the library like this:
`import { VueCsvImport } from 'vue-csv-import/src'`
It's weird but works well. We import directly the index from `/src`

It's seem that's not the correct solution so if you've any clue of what happened please tell us 👍
Thanks!

**Comment by thewhtrabbt22** [comment]
That worked! Thank you! @jgile please update your documentation!
