### ISSUE TITLE
Dist directory missing from NPM package since 4.0.4

### ISSUE THREAD

**Issue by yowkah** [jgile/vue-csv-import#63]
I just updated my npm package and got an error that the module can not be found. It looks like whenever i install the 4.0.4 version versus the 4.0.1 version, the dist directory is missing from the NPM module. 

For now i downgraded to 4.0.1 and changed the package.json locally to refer to the correct axios version to circumvent this.

Could this be user error from my side?

**Comment by jgile** [comment]
nope.  i messed up.  fixed.
