### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by skullsick** [jgile/vue-csv-import#69]
hi! I use vue3 and try to access a CSV locally, map the field and get the selection as an "array" or "object" to process this to to the backend. But I don't get it to work. I used the example from https://jgile.github.io/vue-csv-import/ but how can I access the mapped field array? for what is the "v-model="csv""? I can't access this v-model. maybe you have another example or can put me in the right directoin

**Comment by James-Burgess** [comment]
In the example code, `csv` is a JSON object containing the mapped fields. 
This is only populated once all required fields have been mapped. (Perhaps this is why you are not seeing the data?)

This is the line of code that shows the mapped JSON in the demo:
``` 
<pre class="mt-15" v-if="csv"><code>{{ csv }}</code></pre>
```

If you would like to see the full source for the demo, have a look at the [App.vue](https://github.com/jgile/vue-csv-import/blob/master/src/App.vue)

**Comment by skullsick** [comment]
thanks. yes it could be so easy. now with all required fields, everything works fine. thanks for the quick help
